csusb/models.py
from flask import current_app
from csusb import db
from sqlalchemy import Column, Integer, Text, String, Boolean, \
DateTime

from datetime import datetime

class Participant(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    fairness = db.Column(db.String(120))
    relevance = db.Column(db.String(120))
    first_name = db.Column(db.String(120))
    last_name = db.Column(db.String(120))
    age = db.Column(db.Integer)
    major = db.Column(db.String(120))
    college_name = db.Column(db.String(120))
    academic_year = db.Column(db.Integer)
    photo = db.Column(db.Text)
    score = db.Column(db.Integer)
    eliminated = db.Column(db.Boolean)
    first_round_answers = db.Column(db.Text)
    first_elimination_vote = db.Column(db.Text)
    second_round_answers = db.Column(db.Text)
    second_elimination_vote = db.Column(db.Text)

    def __init__(self, timestamp, fairness, relevance, first_name, last_name, age, major, college_name,
        academic_year, photo="", score=0, eliminated=False):

        self.timestamp = timestamp
        self.fairness = fairness
        self.relevance = relevance
        self.first_name = first_name
        self.last_name = last_name
        self.age = age
        self.major = major
        self.college_name = college_name
        self.academic_year = academic_year
        self.photo = photo
        self.score = score
        self.eliminated = eliminated

class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120))
    photo_url = db.Column(db.String(120))
    rank = db.Column(db.Integer)
    score = db.Column(db.Integer)
    eliminated = db.Column(db.Boolean)

    def __init__(self, name, photo_url, rank=0, score=0, eliminated=False):
        self.name = name
        self.photo_url = photo_url
        self.rank = rank
        self.score = score
        self.eliminated = eliminated


class Version(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer)
    type = db.Column(db.Text)
    rank = db.Column(db.Text)
    round = db.Column(db.Integer)
    eliminated_player = db.Column(db.Text)
    player_comments = db.Column(db.Text)

    def __init__(self, number, type, rank, round, eliminated_player, player_comments):
        self.number = number
        self.type = type
        self.rank = rank
        self.round = round
        self.eliminated_player = eliminated_player
        self.player_comments = player_comments

csusb/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, IntegerField, SelectField, TextAreaField, \
        SubmitField
from wtforms.validators import Required, NumberRange

class ParticipantForm(Form):
    first_name = StringField('First Name', [Required()])
    last_name = StringField('Last Name', [Required()])
    age =  IntegerField('Age', [Required(), \
            NumberRange(min=13, max=100)], \
            description="How old are you?")
    major = StringField('Major', [Required()], \
            description="What is your major?")
    college_name = SelectField('College', [Required()], \
            choices=[('Arts and Letters', 'Arts and Letters'), \
            ('Business and Public Administration', 'Business and Public \
                Administration'),\
            ('Education', 'Education'), \
            ('Natural Sciences', 'Natural Sciences'), \
            ('Social and Behavioral Sciences', 'Social and Behavioral Sciences'),
            ('Extended Learning', 'Extended Learning'), \
            ('I do not know the name', 'I do not know the name')])
    academic_year = SelectField(
        'What is your academic year?',
        [Required()],
        choices=[
            (1, 'Freshman'),
            (2, 'Sophomore'),
            (3, 'Junior'),
            (4, 'Senior-first year'),
            (5, 'Senior-second year'),
            (6, 'Graduate student'),
            (7, 'Other')
        ],
        coerce=int
    )
    submit = SubmitField('Submit Information')

class SecondRoundForm(Form):
    parachute_cord = TextAreaField('Parachute cord')
    duct_tape = TextAreaField('Duct tape')
    plastic_tarp = TextAreaField('Plastic tarp')
    metal_skewers = TextAreaField('Metal skewers')

class ResearcherInfoForm(Form):
    researchers_first_name = StringField('Researcher First Name', [Required()])
    university = StringField('University Name', [Required()])
    research_id_number = IntegerField('Participant Research ID#', [Required()])
    other_id_numbers = StringField('Who is the participant playing against? Enter their research id numbers below (separate by commas)')
    #submit = SubmitField('Submit Information')

class EliminationForm(Form):
    player = SelectField(
            'Select a player for elimination:', [Required()],
             description="Active players appear in the list.",
             choices=[]
             )
    reason = TextAreaField('Why did you choose this player?', \
             [Required()], \
             description="Reason for voting to eliminate chosen player.")
    

csusb/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from config import config
from results import task_results


bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name='default'):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    from main import main as main_blueprint

    @main_blueprint.app_template_filter('participant')
    def participant(s):
        from .models import Participant
        s = Participant.query.filter_by(id=int(s)).first()
        if s:
            return s
        else:
            return None

    app.register_blueprint(main_blueprint)

    @app.context_processor
    def inject_players():
        from .models import Player
        players = Player.query.order_by(Player.name.desc()).all()
        return dict(players=players)

    @app.context_processor
    def inject_results():
        return dict(task_results=task_results)


    return app

csusb/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

csusb/main/views.py
from flask import render_template, request, redirect, url_for, \
        session, current_app, flash, jsonify, send_file, make_response
from . import main
from .. import db
from ..results import task_results
from .forms import ParticipantForm, SecondRoundForm, EliminationForm, ResearcherInfoForm
from ..models import Participant, Player
from werkzeug.utils import secure_filename
from config import config
import os
import random
from itertools import groupby
import csv
import StringIO
from base64 import decodestring

from datetime import datetime


@main.route('/', methods=['GET', 'POST'])
def index():
    session.pop('university', None)
    session.pop('researchers_first_name', None)
    session.pop('order', None)
    session.pop('participant_id', None)
    form = ResearcherInfoForm()
    if form.validate_on_submit():
        session['university'] = form.university.data
        session['researchers_first_name'] = form.researchers_first_name.data
        return redirect(url_for('main.setup'))
    return render_template('index.html', form=form)


@main.route('/setup')
def setup():
    return render_template('setup.html')


@main.route('/api/first_round_task/<order>', methods=['GET', 'POST'])
def api_first_round_task(order=None):
    session['order'] = {}
    for index, item in enumerate(order.split(",")):
        session['order'][item] = index + 1

    print session['order']
    return jsonify({'order': order})


@main.route('/participant', methods=['GET', 'POST'])
def participant():
    form = ParticipantForm()
    """Get a randomly selected type. And setup new test."""
    fairness_options = ['fair', 'unfair']
    relevance_options = ['relevant', 'irrelevant']
    if session.get('override_fairness', None):
        fairness = session['override_fairness']
    else:
        fairness = random.choice(fairness_options)
    if session.get('override_relevance', None):
        relevance = session['override_relevance']
    else:
        relevance = random.choice(relevance_options)

    #Reset session to remove the previous participant

    players = Player.query.order_by(Player.name.desc()).all()

    #Reset scores, rank, and elimination status
    for player in players:
        player.rank = None
        player.score = 0
        player.eliminated = False
        db.session.commit()

    if request.method == 'POST':
        if form.validate_on_submit():
            participant = Participant(
                    timestamp=datetime.now(),
                    fairness=fairness,
                    relevance=relevance,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    age=form.age.data,
                    major=form.major.data,
                    college_name=form.college_name.data,
                    academic_year=form.academic_year.data
            )

            db.session.add(participant)
            db.session.commit()

            session['participant_id'] = participant.id

            return redirect('/photo')
    return render_template('participant.html',
            title='Participant Registration',
            form=form)

@main.route('/photo', methods=['GET', 'POST'])
def photo():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'imgBase64' not in request.form:
            flash('No file part')
            return redirect(request.url)
        data_uri = request.form['imgBase64']
        data = decodestring(data_uri.split(',', 1)[-1])
        participant = Participant.query.filter_by(id=session['participant_id']).first()
        filename = participant.first_name + '_' + participant.last_name + '.jpg'
        path_to_photo = os.path.join(config['default'].UPLOAD_FOLDER, filename)
        with open(path_to_photo, 'wb') as f:
            f.write(data)
        participant.photo = filename
        db.session.commit()
        return redirect('/staging')
    return render_template('photo.html')

@main.route('/staging')
def staging():
    return render_template('staging.html')

@main.route('/firstround')
def first_round():
    return render_template('firstround/task.html')

@main.route('/firstround/reminder')
def first_round_reminder():
    return render_template('firstround/reminder.html')

@main.route('/firstround/scores')
def first_round_scores():

    rankings = []
    participant = Participant.query.filter_by(id=session['participant_id']).first()
    participant.score = task_results[participant.relevance][participant.fairness]['r1']['rankings']['Participant']
    db.session.commit()

    rankings.append([participant.first_name, participant.score])

    players = Player.query.order_by(Player.name.desc()).all()
    for player in players:
        player.score = task_results[participant.relevance][participant.fairness]['r1']['rankings'].get(player.name, 0)
        rankings.append([player.name, player.score])
        db.session.commit()

    rankings = sorted(rankings, key=lambda x: x[1], reverse=True)
    for rank, (_, grp) in enumerate(groupby(rankings, key=lambda xs: xs[1]), 1):
        for x in grp:
            x.append(rank)


    return render_template('firstround/scores.html', rankings=rankings)

@main.route('/secondround')
def second_round():
    form = SecondRoundForm()
    participant = Participant.query.filter_by(id=session['participant_id']).first()
    participant.score = 0
    db.session.commit()
    players = Player.query.order_by(Player.name.desc()).all()
    for player in players:
        player.score = 0
        db.session.commit()
    return render_template('secondround/task.html', form=form)

@main.route('/secondround/reminder')
def second_round_reminder():
    return render_template('secondround/reminder.html')

@main.route('/secondround/scores')
def second_round_scores():
    rankings = []
    participant = Participant.query.filter_by(id=session['participant_id']).first()
    participant.score = task_results[participant.relevance][participant.fairness]['r2']['rankings']['Participant']
    db.session.commit()
    rankings.append([participant.first_name, participant.score])

    players = Player.query.order_by(Player.name.desc()).all()
    for player in players:
        player.score = task_results[participant.relevance][participant.fairness]['r2']['rankings'].get(player.name, 0)
        if player.eliminated:
            pass
        else:
            rankings.append([player.name, player.score])
        db.session.commit()

    rankings = sorted(rankings, key=lambda x: x[1], reverse=True)
    for rank, (_, grp) in enumerate(groupby(rankings, key=lambda xs: xs[1]), 1):
        for x in grp:
            x.append(rank)

    return render_template('secondround/scores.html', rankings=rankings)

@main.route('/firstround/elimination', methods=['GET', 'POST'])
@main.route('/firstround/elimination/<modify>', methods=['GET', 'POST'])
def first_elimination(modify=None):
    participant = Participant.query.filter_by(id=session['participant_id']).first()
    form = EliminationForm()
    choices = task_results[participant.relevance][participant.fairness]['r1']['rankings']
    form.player.choices = [(key, key) for key, value in choices.items() if key != 'Participant']
    form.player.choices.insert(0, ('', ''))

    if form.validate_on_submit():
        participant = Participant.query.filter_by(id=session['participant_id']).first()
        participant.first_elimination_vote = form.player.data
        participant.first_round_answers = form.reason.data
        db.session.commit()

        eliminated_player = Player.query.filter_by(name=task_results[participant.relevance][participant.fairness]['r1']['player_voted_off']).first()
        eliminated_player.eliminated = True
        db.session.commit()

        return redirect(url_for('main.first_elimination', modify='results'))
    return render_template('elimination.html', form=form, modify=modify)

@main.route('/secondround/elimination', methods=['GET', 'POST'])
@main.route('/secondround/elimination/<modify>', methods=['GET', 'POST'])
def second_elimination(modify=None):
    participant = Participant.query.filter_by(id=session['participant_id']).first()
    form = EliminationForm()
    choices = task_results[participant.relevance][participant.fairness]['r2']['rankings']
    eliminated_player = task_results[participant.relevance][participant.fairness]['r2']['player_voted_off']

    form.player.choices = [(key, key) for key, value in choices.items() if key != 'Participant']
    form.player.choices.insert(0, ('', ''))
    if form.validate_on_submit():
        participant = Participant.query.filter_by(id=session['participant_id']).first()
        participant.second_elimination_vote = form.player.data
        participant.second_round_answers = form.reason.data
        if eliminated_player == 'Participant':
            participant.eliminated = True
        db.session.commit()
        return redirect(url_for('main.second_elimination', modify='second_results'))
    return render_template('elimination.html', form=form, modify=modify)


@main.route('/final-step', methods=['GET', 'POST'])
def final_step():
    return render_template('final_step.html')


@main.route('/change-fairness/<modify>', methods=['GET', 'POST'])
def change_fairness(modify=None):
    if modify == '001':
        session['override_fairness'] = 'unfair'
        session['override_relevance'] = 'relevant'
    elif modify == '002':
        session['override_fairness'] = 'fair'
        session['override_relevance'] = 'relevant'
    elif modify == '003':
        session['override_fairness'] = 'unfair'
        session['override_relevance'] = 'irrelevant'
    elif modify == '004':
        session['override_fairness'] = 'fair'
        session['override_relevance'] = 'irrelevant'
    elif modify == 'clear':
        session.pop('override_fairness', None)
        session.pop('override_relevance', None)
    return redirect(url_for('main.admin'))

csusb/templates/admin.html
{% extends "base.html" %}

{% block page_content %}

<div class="container">
    <a href="{{url_for('main.to_csv')}}" class="btn btn-primary">Download CSV</a>

    <a href="{{url_for('main.change_fairness', modify='001')}}" class="btn
    {% if ('override_fairness' in session) and ('override_relevance' in session)%}
        {% if (session['override_fairness'] == 'unfair') and (session['override_relevance'] == 'relevant')%}
            btn-primary
        {% else %}
            btn-default
        {% endif%}
    {% else %}
        btn-default
    {% endif %}">Only Relevant Unfair</a>

    <a href="{{url_for('main.change_fairness', modify='002')}}" class="btn
    {% if ('override_fairness' in session) and ('override_relevance' in session)%}
        {% if (session['override_fairness'] == 'fair') and (session['override_relevance'] == 'relevant')%}
            btn-primary
        {% else %}
            btn-default
        {% endif%}
    {% else %}
        btn-default
    {% endif %}">Only Relevant Fair</a>

    <a href="{{url_for('main.change_fairness', modify='003')}}" class="btn
    {% if ('override_fairness' in session) and ('override_relevance' in session)%}
        {% if (session['override_fairness'] == 'unfair') and (session['override_relevance'] == 'irrelevant')%}
            btn-primary
        {% else %}
            btn-default
        {% endif%}
    {% else %}
        btn-default
    {% endif %}">Only Irrelevant Unfair</a>

    <a href="{{url_for('main.change_fairness', modify='004')}}" class="btn
    {% if ('override_fairness' in session) and ('override_relevance' in session)%}
        {% if (session['override_fairness'] == 'fair') and (session['override_relevance'] == 'irrelevant')%}
            btn-primary
        {% else %}
            btn-default
        {% endif%}
    {% else %}
        btn-default
    {% endif %}">Only Irrelevant Fair</a>

    <a href="{{url_for('main.change_fairness', modify='clear')}}" class="btn {% if ('override_fairness' in session) and ('override_relevance' in session)%}btn-default{% else %} btn-primary {% endif %}">Random Experience</a>
    <a href="{{url_for('main.delete_all')}}" class="btn btn-danger">Delete All</a>
    <br>
    <br>

</div>


<table class="table">
    <tr>
        <th>Actions</th>
        <th>id</th>
        <th>timestamp</th>
        <th>fairness</th>
        <th>relevance</th>
        <th>first name</th>
        <th>last name</th>
        <th>age</th>
        <th>major</th>
        <th>college</th>
        <th>academic year</th>
        <th>eliminated</th>
        <th>first round answers</th>
        <th>second round answers</th>
        <th>first round vote</th>
        <th>second round vote</th>
    </tr>
    {% for participant in participants %}
    <tr>
        <td><a href="{{ url_for('main.delete_all', id=participant.id)}}">delete</a></td>
        <td>{{participant.id}}</td>
        <td>{{participant.timestamp}}</td>
        <td>{{participant.fairness}}</td>
        <td>{{participant.relevance}}</td>
        <td>{{participant.first_name}}</td>
        <td>{{participant.last_name}}</td>
        <td>{{participant.age}}</td>
        <td>{{participant.major}}</td>
        <td>{{participant.college_name}}</td>
        <td>{{participant.academic_year}}</td>
        <td>{{participant.eliminated}}</td>
        <td>{{participant.first_round_answers}}</td>
        <td>{{participant.second_round_answers}}</td>
        <td>{{participant.first_elimination_vote}}</td>
        <td>{{participant.second_elimination_vote}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

csusb/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% if session['university'] %} {{ session['university'] }} {% else %} CSUSB {% endif %} Survivor{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico')
}}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}"
                 type="image/x-icon">
{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">{% if session['university'] %} {{ session['university'] }} {% else %} CSUSB {% endif %} Survivor</a>
        </div>
        <div class="navbar-collapse collapse">
          <p class="navbar-text pull-right">
            <span class="user-info" style="color:white">
              {% if session.participant_id %}
              {% set p = (session['participant_id'] | participant) %}
              {{ p.first_name }}
              {{ p.last_name }}

              {% if p.relevance == 'relevant' %}
                {% if p.fairness == 'fair' %}
                  002
                {% else %}
                  001
                {% endif %}

              {% else %}
                  {% if p.fairness == 'fair' %}
                    004
                  {% else %}
                    003
                  {% endif %}
              {% endif %}

              {% endif %}
            </span>
            <span id="time-notification-area"></span>
            <span id="loading-bar"></span>
          </p>
            <ul class="nav navbar-nav">

            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}
<noscript>
  <div id="noscript-warning bg-danger">This site will not work properly without Javascript. Please enable it in your browser.</div>
</noscript>

csusb/templates/elimination.html
{% extends "game-layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{% if session['university'] %} {{ session['university'] }} {% else %} CSUSB {% endif %} Survivor &ndash; Eliminate Member{% endblock %}

  {% block workspace %}


  {% if modify == 'results' %}
  <h2>Your Team's vote has been determined!</h2>
  <p id="elimination-results" class="bg-info" style="font-size:30px"><strong>Sorry {{ task_results[(session['participant_id'] | participant).relevance][(session['participant_id'] | participant).fairness]['r1']['player_voted_off'] }}, you received
  the most elimination votes. You have been voted off the island!</strong></p>

  <p>Here are the reasons your teammates gave for their choice:</p>
  <ul>
    {% for comment in task_results[(session['participant_id'] | participant).relevance][(session['participant_id'] | participant).fairness]['r1']['comments'] %}
    <li>{{ comment }}</li>
    {% endfor %}
    {% if (task_results[(session['participant_id'] | participant).relevance][(session['participant_id'] | participant).fairness]['r1']['player_voted_off']) == (session['participant_id'] | participant).first_elimination_vote %}
    <li>{{ (session['participant_id'] | participant).first_round_answers }}</li>
    {% endif %}
  </ul>
  <a href="{{url_for('main.second_round')}}" class="btn btn-primary">Next Round</a>


{% elif modify == 'second_results'%}
  <h2>Your Team's vote has been determined!</h2>
  <p id="elimination-results" class="bg-info" style="font-size:30px"> <strong>Sorry {{ (session['participant_id'] | participant).first_name }}, you received
  the most elimination votes. You have been voted off the island!</strong></p>

  <p>Here are the reasons your teammates gave for their choice:</p>
  <ul>
    {% for comment in task_results[(session['participant_id'] | participant).relevance][(session['participant_id'] | participant).fairness]['r2']['comments'] %}
    <li>{{ comment }}</li>
    {% endfor %}
    {% if (task_results[(session['participant_id'] | participant).relevance][(session['participant_id'] | participant).fairness]['r2']['player_voted_off']) == (session['participant_id'] | participant).second_elimination_vote %}
    <li>{{ (session['participant_id'] | participant).second_round_answers }}</li>
    {% endif %}
  </ul>

  <!-- <h2>Sorry, you will finish the strategy tasks on your own and will NOT have a chance to win 1, 3, or 5 lottery tickets for a $100.00 draw!
Goodbye!
</h2> -->

<a class="btn btn-primary" href="{{ url_for('main.final_step')}}">Next</a>


{% else %}
{% block description %}
{%- if request.url_rule.endpoint == "main.first_elimination" %}
<strong><h3 class="bg-info" style="font-size:30px">Remember: higher scores mean better performance!</h3></strong>
{% endif %}
{% if request.url_rule.endpoint == "main.second_elimination" %}
<strong><h3 class="bg-info" style="font-size:30px">Remember: higher scores mean better performance!</h3></strong>
{% endif %}
{% endblock %}


  <h2>Eliminate a Team Member</h2>
  {{ wtf.quick_form(form, id="myForm") }}
  <style>
  #myProgress {
    position: relative;
    width: 100%;
    height: 30px;
    background-color: #ddd;
  }

  #myBar {
    position: absolute;
    width: 2%;
    height: 100%;
    background-color: #4CAF50;
  }

  #label {
    text-align: center;
    line-height: 30px;
    color: white;
  }
  </style>
  <body>

  <div id="myProgress2" style="display:none;">
  <h1>Collecting Scores</h1>

  <div id="myProgress">
    <div id="myBar">
      <div id="label">2%</div>
    </div>
  </div>
  </div>

  <br>
  <button id="button1" class="btn" onclick="move()">Submit</button>

  <script>
  function move() {
    var elem = document.getElementById("myBar");
    var width = 2;
    var id = setInterval(frame, 240);
    $("#button1").addClass("disabled");
    $("#myProgress2").show();
    function frame() {
      if (width >= 100) {
        clearInterval(id);
        document.getElementById("myForm").submit();
      } else {
        width++;
        elem.style.width = width + '%';
        document.getElementById("label").innerHTML = width * 1  + '%';
      }
    }

  }
  </script>
  <div id="elimination-results" class="bg-info"></div>
  {% endif %}
  {% endblock %}

csusb/templates/final_step.html
{% extends "game-layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{% if session['university'] %} {{ session['university'] }} {% else %} CSUSB {% endif %} Survivor &ndash; Eliminate Member{% endblock %}

  {% block workspace %}










  <h2>Sorry, you will finish the strategy tasks on your own and will NOT have a chance to win 1, 3, or 5 lottery tickets for a $100.00 draw!
Goodbye!
</h2>

<a id="last_step" class="btn btn-primary">Finish</a>
<script
  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
  crossorigin="anonymous"></script>
<script type="text/javascript">
    $('#last_step').click(function() {
        $(this).hide()
    })
</script>



  {% endblock %}

csusb/templates/game-layout.html
{% extends "base.html" %}

{% block page_content %}
<div class="row">
    <div class="col-md-5">
        <div class="row">
            <div class="col-md-4">
            <div class="table-responsive">
                <table class="table">
                    <h3>Your team:</h3>
                    <thead></thead>
                    <tbody>
                      {% if session.participant_id %}
                        <th class="{% if (session['participant_id'] | participant).eliminated %}eliminated{% endif %}">{{ (session['participant_id'] | participant).first_name }}
                          <img style="width:75px;height:75px;" src="/static/img/uploads/{{ (session['participant_id'] | participant).photo }}" class="img-rounded">
                            <small>{% if (session['participant_id'] | participant).score %}
                              {{ (session['participant_id'] | participant).score }} points
                              {% else %}
                              0 Points
                            {% endif %}
                          </small>
                            <small>{% if (session['participant_id'] | participant).eliminated %}Eliminated!{% endif %}</small>
                        </th>
                        {% endif %}

                        {% for player in players %}
                        <th class="{% if player.eliminated %}eliminated{% endif %}">{{ player.name }}
                          <img src="/static/{{ player.photo_url }}" class="img-rounded" height="75px" width="75px">
                            <small>{{ player.score }} points</small>
                            <small>{% if player.eliminated %}Eliminated!{% endif %}</small>
                        </th>
                        {% endfor %}

                    </tbody>
                  </table>
            </div>
            </div>
        </div>
        <div class="description">{% block description %}{% endblock %}</div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6"><div class="workspace">{% block workspace %}{% endblock %}</div></div>
</div>



{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

csusb/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{% if session['university'] %} {{ session['university'] }} {% else %} CSUSB {% endif %} Survivor &ndash; Welcome{% endblock %}

{% block page_content %}
<h1 class="text-center">Researcher, please complete this section!</h1>

<p class="lead">Who is the participant playing against? Enter their research ID numbers below.</p>
<br />
{{ wtf.quick_form(form, id="myForm") }}

<style>
#myProgress {
  position: relative;
  width: 100%;
  height: 30px;
  background-color: #ddd;
}

#myBar {
  position: absolute;
  width: 2%;
  height: 100%;
  background-color: #4CAF50;
}

#label {
  text-align: center;
  line-height: 30px;
  color: white;
}
</style>
<body>

<div id="myProgress2" style="display:none;">
<h1>Setting up team</h1>

<div id="myProgress">
  <div id="myBar">
    <div id="label">2%</div>
  </div>
</div>
</div>

<br>
<button id="button1" class="btn" onclick="move()">Submit</button>

<script>
function move() {
  var elem = document.getElementById("myBar");
  var width = 2;
  var id = setInterval(frame, 240);
  $("#button1").addClass("disabled");
  $("#myProgress2").show();
  function frame() {
    if (width >= 100) {
      clearInterval(id);
      document.getElementById("myForm").submit();
    } else {
      width++;
      elem.style.width = width + '%';
      document.getElementById("label").innerHTML = width * 1  + '%';
    }
  }

}
</script>

{% endblock %}